export const sessionsData = [
  {
    id: "session-1",
    date: "2024-01-25",
    contenderOne: "Player A",
    contenderTwo: "Player B",
    contenderOneWon: false,
  },
  {
    id: "session-2",
    date: "2024-01-25",
    contenderOne: "Player A",
    contenderTwo: "Player B",
    contenderOneWon: true,
  },
  {
    id: "session-3",
    date: "2024-01-25",
    contenderOne: "Player C",
    contenderTwo: "Player D",
    contenderOneWon: true,
  },
  {
    id: "session-4",
    date: "2024-01-24",
    contenderOne: "Player B",
    contenderTwo: "Player C",
    contenderOneWon: true,
  },
  {
    id: "session-5",
    date: "2024-01-24",
    contenderOne: "Player A",
    contenderTwo: "Player D",
    contenderOneWon: false,
  },
  {
    id: "session-6",
    date: "2024-01-23",
    contenderOne: "Player C",
    contenderTwo: "Player A",
    contenderOneWon: false,
  },
  {
    id: "session-7",
    date: "2024-01-22",
    contenderOne: "Player B",
    contenderTwo: "Player C",
    contenderOneWon: true,
  },
  {
    id: "session-8",
    date: "2024-01-22",
    contenderOne: "Player D",
    contenderTwo: "Player A",
    contenderOneWon: true,
  },
  {
    id: "session-9",
    date: "2024-01-22",
    contenderOne: "Player B",
    contenderTwo: "Player D",
    contenderOneWon: false,
  },
  {
    id: "session-10",
    date: "2024-01-21",
    contenderOne: "Player A",
    contenderTwo: "Player D",
    contenderOneWon: true,
  },
  {
    id: "session-11",
    date: "2024-01-20",
    contenderOne: "Player C",
    contenderTwo: "Player B",
    contenderOneWon: true,
  },
  {
    id: "session-12",
    date: "2024-01-19",
    contenderOne: "Player D",
    contenderTwo: "Player A",
    contenderOneWon: false,
  },
  {
    id: "session-13",
    date: "2024-01-19",
    contenderOne: "Player B",
    contenderTwo: "Player C",
    contenderOneWon: true,
  },
  {
    id: "session-14",
    date: "2024-01-18",
    contenderOne: "Player A",
    contenderTwo: "Player C",
    contenderOneWon: false,
  },
  {
    id: "session-15",
    date: "2024-01-17",
    contenderOne: "Player D",
    contenderTwo: "Player B",
    contenderOneWon: true,
  },
  {
    id: "session-16",
    date: "2024-01-17",
    contenderOne: "Player A",
    contenderTwo: "Player C",
    contenderOneWon: true,
  },
  {
    id: "session-17",
    date: "2024-01-17",
    contenderOne: "Player B",
    contenderTwo: "Player D",
    contenderOneWon: false,
  },
  {
    id: "session-18",
    date: "2024-01-16",
    contenderOne: "Player C",
    contenderTwo: "Player A",
    contenderOneWon: true,
  },
  {
    id: "session-19",
    date: "2024-01-15",
    contenderOne: "Player D",
    contenderTwo: "Player B",
    contenderOneWon: false,
  },
  {
    id: "session-20",
    date: "2024-01-15",
    contenderOne: "Player A",
    contenderTwo: "Player C",
    contenderOneWon: true,
  },
];

export const decksData = [
  {
    id: "deck-1",
    name: "Red Deck Wins",
    owner: "Player A",
    colors: ["red"],
    description: "Aggressive red deck focused on quick damage and burn spells",
    wins: 3,
    losses: 2,
  },
  {
    id: "deck-2",
    name: "Blue Control",
    owner: "Player B",
    colors: ["blue"],
    description: "Control deck with counterspells and card draw",
    wins: 2,
    losses: 3,
  },
  {
    id: "deck-3",
    name: "Green Ramp",
    owner: "Player A",
    colors: ["green"],
    description: "Mana ramp deck with big creatures",
    wins: 1,
    losses: 1,
  },
  {
    id: "deck-4",
    name: "White Weenie",
    owner: "Player B",
    colors: ["white"],
    description: "Small white creatures with equipment and auras",
    wins: 2,
    losses: 1,
  },
  {
    id: "deck-5",
    name: "Jeskai Control",
    owner: "Player A",
    colors: ["white", "blue", "red"],
    description: "Three-color control deck with removal and counterspells",
    wins: 4,
    losses: 1,
  },
  {
    id: "deck-6",
    name: "Golgari Midrange",
    owner: "Player C",
    colors: ["black", "green"],
    description:
      "Midrange deck with graveyard synergies and efficient creatures",
    wins: 3,
    losses: 2,
  },
  {
    id: "deck-7",
    name: "Izzet Spells",
    owner: "Player D",
    colors: ["blue", "red"],
    description: "Spellslinger deck focused on instants and sorceries",
    wins: 2,
    losses: 3,
  },
];
